<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <CassotisVersion>1.26.1</CassotisVersion>
    <CassotisVersionQuad>1.26.1.0</CassotisVersionQuad>
    <CassotisVersionMajor>1</CassotisVersionMajor>
    <CassotisVersionMinor>26</CassotisVersionMinor>
    <CassotisVersionRelease>1</CassotisVersionRelease>
    <CassotisVersionBuild>0</CassotisVersionBuild>
  </PropertyGroup>
</Project>
